wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
batch_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.0001
modelname:
  desc: null
  value: IPT
output_dir:
  desc: null
  value: .
weight_decay:
  desc: null
  value: 0.0001
